version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: ${TARGET:-development}
    ports:
      - "3000:3000"
    volumes:
    - ./frontend:/app
    - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}

  backend:
    build:
      context: ./backend
      target: ${TARGET:-development}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - WEIGHT_URGENCY=0.30
      - WEIGHT_IMPORTANCE=0.30
      - WEIGHT_IMPACT=0.20
      - WEIGHT_VALUE=0.20
      - EFFORT_PENALTY=0.15
      - DUE_SOON_DAYS=5
      - DUE_SOON_MAX_BONUS=0.15
